services:
  frontend:
    image: ${REGISTRY_URL}/${REGISTRY_USER}/safar-frontend:latest
    container_name: safar-frontend
    restart: unless-stopped
    env_file:
      - .env
    networks:
      - shared-network

networks:
  shared-network:
    external: true
